In [64]:
!ls

ch1_basics.ipynb  ch2_data.ipynb  Untitled.ipynb

In [65]:
!ls ../Data

acc.csv		       Lung Cap_Random.csv
ACC_matched.xlsx       Lung Cap_Random_csv.csv
agri		       mid_term
Autos.xlsx	       New Microsoft Excel Worksheet.xlsx
Crude_Futures.csv      Regression_TCS.csv
Crude_spot.csv	       RELIANCE_Bhavcopy_xls.xls
Data.csv	       RELIANCE_Bhavcopy_xlsx.xlsx
Data File.csv	       RELIANCE_close price.csv
Data File.xlsx	       RELIANCE_number of trades.csv
Data_for_Agri.zip      RELIANCE_trade quantity.csv
Data_for_mid-term.zip  sddg.xlsx
Data.xlsx	       TCS.csv
Lung Cap_Random2.csv

In [66]:
import pandas as pd

In [67]:
df=pd.read_excel("../Data/Autos.xlsx", sheet_name="Data")

In [68]:
df.head()

,Year,Quarter,Sales,GNP,Unemp,Int,Q1,Q2,Q3,LagGNP,LagUnemp,LagInt
0,79,1,NaN,2541,5.9,9.4,NaN,NaN,NaN,NaN,NaN,NaN
1,79,2,2910.0,2640,5.7,9.4,0.0,1.0,0.0,2541.0,5.9,9.4
2,79,3,2562.0,2595,5.9,9.7,0.0,0.0,1.0,2640.0,5.7,9.4
3,79,4,2385.0,2701,6.0,11.9,0.0,0.0,0.0,2595.0,5.9,9.7
4,80,1,2520.0,2785,6.2,13.4,1.0,0.0,0.0,2701.0,6.0,11.9

In [69]:
df.drop(0)

,Year,Quarter,Sales,GNP,Unemp,Int,Q1,Q2,Q3,LagGNP,LagUnemp,LagInt
1,79,2,2910.0,2640,5.7,9.4,0.0,1.0,0.0,2541.0,5.9,9.4
2,79,3,2562.0,2595,5.9,9.7,0.0,0.0,1.0,2640.0,5.7,9.4
3,79,4,2385.0,2701,6.0,11.9,0.0,0.0,0.0,2595.0,5.9,9.7
4,80,1,2520.0,2785,6.2,13.4,1.0,0.0,0.0,2701.0,6.0,11.9
5,80,2,2142.0,2509,7.3,9.6,0.0,1.0,0.0,2785.0,6.2,13.4
6,80,3,2130.0,2570,7.7,9.2,0.0,0.0,1.0,2509.0,7.3,9.6
7,80,4,2190.0,2667,7.4,13.6,0.0,0.0,0.0,2570.0,7.7,9.2
8,81,1,2370.0,2878,7.4,14.4,1.0,0.0,0.0,2667.0,7.4,13.6
9,81,2,2208.0,2835,7.4,15.3,0.0,1.0,0.0,2878.0,7.4,14.4
10,81,3,2196.0,2897,7.4,15.1,0.0,0.0,1.0,2835.0,7.4,15.3
11,81,4,1758.0,2744,8.3,11.8,0.0,0.0,0.0,2897.0,7.4,15.1
12,82,1,1944.0,2582,8.8,12.8,1.0,0.0,0.0,2744.0,8.3,11.8
13,82,2,2094.0,2613,9.4,12.4,0.0,1.0,0.0,2582.0,8.8,12.8
14,82,3,1911.0,2529,10.0,9.3,0.0,0.0,1.0,2613.0,9.4,12.4
15,82,4,2031.0,2544,10.7,7.9,0.0,0.0,0.0,2529.0,10.0,9.3
16,83,1,2046.0,2633,10.4,7.8,1.0,0.0,0.0,2544.0,10.7,7.9
17,83,2,2502.0,2878,10.1,8.4,0.0,1.0,0.0,2633.0,10.4,7.8
18,83,3,2238.0,3051,9.4,9.1,0.0,0.0,1.0,2878.0,10.1,8.4
19,83,4,2394.0,3274,8.5,8.8,0.0,0.0,0.0,3051.0,9.4,9.1
20,84,1,2586.0,3594,7.9,9.2,1.0,0.0,0.0,3274.0,8.5,8.8
21,84,2,2898.0,3774,7.5,9.8,0.0,1.0,0.0,3594.0,7.9,9.2
22,84,3,2448.0,3861,7.5,10.3,0.0,0.0,1.0,3774.0,7.5,9.8
23,84,4,2460.0,3919,7.2,8.8,0.0,0.0,0.0,3861.0,7.5,10.3
24,85,1,2646.0,4040,7.4,8.2,1.0,0.0,0.0,3919.0,7.2,8.8
25,85,2,2988.0,4133,7.3,7.5,0.0,1.0,0.0,4040.0,7.4,8.2
26,85,3,2967.0,4303,7.1,7.1,0.0,0.0,1.0,4133.0,7.3,7.5
27,85,4,2439.0,4393,7.0,7.2,0.0,0.0,0.0,4303.0,7.1,7.1
28,86,1,2598.0,4560,7.1,8.9,1.0,0.0,0.0,4393.0,7.0,7.2
29,86,2,3045.0,4587,7.1,7.7,0.0,1.0,0.0,4560.0,7.1,8.9
30,86,3,3213.0,4716,6.9,7.4,0.0,0.0,1.0,4587.0,7.1,7.7
31,86,4,2685.0,4796,6.8,7.4,0.0,0.0,0.0,4716.0,6.9,7.4

In [70]:
df.columns

Index(['Year', 'Quarter', 'Sales', 'GNP', 'Unemp', 'Int', 'Q1', 'Q2', 'Q3',
       'LagGNP', 'LagUnemp', 'LagInt'],
      dtype='object')

In [71]:
X=df[['Q1', 'Q2', 'Q3','LagGNP', 'LagUnemp', 'LagInt']]

In [72]:
y=df[["Sales"]]

In [73]:
import statsmodels.api as sm

In [74]:
est = sm.OLS(y, X, missing="drop").fit()

In [75]:
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.986
Model:                            OLS   Adj. R-squared:                  0.983
Method:                 Least Squares   F-statistic:                     301.8
Date:                Tue, 23 Apr 2019   Prob (F-statistic):           4.54e-22
Time:                        13:32:47   Log-Likelihood:                -219.46
No. Observations:                  31   AIC:                             450.9
Df Residuals:                      25   BIC:                             459.5
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Q1           216.5414    165.374      1.309      0.202    -124.054     557.136
Q2           418.4191    161.075      2.598      0.016      86.680     750.159
Q3           260.6605    159.583      1.633      0.115     -68.007     589.328
LagGNP         0.4977      0.057      8.696      0.000       0.380       0.616
LagUnemp      51.5984     31.295      1.649      0.112     -12.855     116.051
LagInt        18.3070     19.402      0.944      0.354     -21.653      58.267
==============================================================================
Omnibus:                        3.914   Durbin-Watson:                   0.805
Prob(Omnibus):                  0.141   Jarque-Bera (JB):                3.193
Skew:                           0.785   Prob(JB):                        0.203
Kurtosis:                       2.919   Cond. No.                     1.32e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.32e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""